# Generated by Django 2.1.4 on 2018-12-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('command',)},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('role',)},
        ),
        migrations.RenameField(
            model_name='command',
            old_name='name',
            new_name='command',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role',
        ),
        migrations.AddField(
            model_name='tguser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmapp.Role'),
        ),
    ]
